# Generated by Django 4.2.4 on 2023-08-30 12:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('heading', models.TextField(default='')),
                ('text', models.TextField(default='')),
                ('image', models.ImageField(upload_to='media/')),
            ],
        ),
    ]
