# Generated by Django 4.2.4 on 2023-09-04 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='heading',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='publication',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='text',
            field=models.TextField(blank=True, default=''),
        ),
    ]
