# Generated by Django 4.2.4 on 2023-09-04 21:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = False

    dependencies = [
    ]

    operations = [
        migrations.AddField(
            model_name='Publication',
            name="topics",
            field=models.TextField(default='', blank=True),
        ),
        migrations.AddField(
            model_name='Publication',
            name="date",
            field=models.DateTimeField(),
        ),
    ]
