# Generated by Django 4.2.8 on 2024-01-17 13:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='publication',
            name='topics',
            field=models.TextField(blank=True, default=''),
        ),
    ]
